### PR TITLE
fix: Regex extracting claims (addressing #420)

### LINKED ISSUE #420: http - incorrect regex causing claim parsing to fail
Incorrect regex in `packages/http/httpx/kiota_http/httpx_request_adapter.py` causes downstream impact decoding the base-64 encoded claim in reponse.

**Environment:**
Python Version: 3.13.0
kiota-python version: 1.6.3 
OS: Windows 11 Version 10.0.22621 Build 22621

**Stack trace:**
Image

**Describe the bug:**
Calling `get_authoritzation_token`  to retrieve a bearer token using the `AzureIdentityAccessTokenProvider` class generates a `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 109: invalid start byte` exception.

The issue stems from the incorrect regex used in the `retry_cae_response_if_required` function in file `packages/http/httpx/kiota_http/httpx_request_adapter.py`. The following regex attempts to extract the base-64 encoded claims included in the value of the `WWW-Authenticate` header:

`claims="(.+)"`

However, the `.+` greedily matches all characters up to the final `"` present in the `WWW-Authenticate` header. If the value contains any other keys (e.g. `Pop realm`, `authorization_uri`, `client_id` etc.) they are also captured.

For example, suppose the value of the `WWW-Authenticate` header is:
`claims="eyJhYsdgsXSd", PoP realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", nonce="eyJ0e"`

The expected behavior of the regex is to match `claims="eyJhYsdgsXSd"`; however, it instead matches the full string up to an including the final `...J0e"`. The function subsequent splitting on the string `="` means the "base-64" encoded claims passed to subsequent functions would be the string `eyJhYsdgsXSd", PoP realm`. As this is an invalid base-64 encoded string, when it is decoded it raises a `UnicodeDecodeError` exception.

**Suggested fix:**
Replace the regex with `claims="([^"]+)"` and use the first matching group to extract the base-64 encoded value. I will be raising a PR shortly.

**Expected behavior:**
A bearer token would be returned.

### PR DESCRIPTION
**Pull request by Mrfence97**
## Overview

Updates the regex extracting the base-64 encoded claims in the WWW-Authenticate header. More details provided in issue #420.

## Related Issue

Fixes #420

### CODE REVIEW

**Review by baywet — DISMISSED** [review]
Thanks for the contribution!

**Review by musale — DISMISSED** [review]

**Comment by musale** [comment]
@Mrfence97 could you please check some tests are failing.

**Review by Ndiritu — COMMENTED** [review]
Adding a unit test for this would be great.

**Comment by Mrfence97** [comment]
> @Mrfence97 could you please check some tests are failing.

The failing test was due to a bug in the test. In particular, there is a bug in the assertion of the `test_retries_on_cae_failure` test in `http/httpx/tests/test_httpx_request_adapter.py`. The mock claim entered in `mock_cae_failure_response` in `http/httpx/tests/conftest.py` ends with a `=`. It is unclear how this test ever passed previously!

I've added a commit to fix the test.

**Comment by Mrfence97** [comment]
> Adding a unit test for this would be great.

Unfortunately I don't know your testing framework well enough to implement something myself, but hopefully somebody at Microsoft can do it!

**Comment by Mrfence97** [comment]
@microsoft-github-policy-service agree

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by baywet — APPROVED** [review]

**Review by andrueastman — APPROVED** [review]

**Pull request merged**
